Repository hyperledger/fabric-private-chaincode, pull requests merged in 2019-05, with the labels that each got.

#52 One make to rule them all
  .gitignore
  Makefile
  README.md
  build.mk
  cmake/NanoPB.cmake
  common/.gitignore
  config.mk
  ecc/.gitignore
  ecc/Makefile
  ecc/README.md
  ecc/enclave/include
  ecc/enclave/lib
  ecc/enclave/mrenclave.go
  ecc_enclave/.gitignore
  ecc_enclave/CMakeLists.txt
  ecc_enclave/Makefile
  ecc_enclave/sgxcclib/CMakeLists.txt
  ercc/.gitignore
  ercc/Makefile
  ercc/README.md
  fabric/README.md
  tlcc/.gitignore
  tlcc/Makefile
  tlcc/README.md
  tlcc/enclave/include
  tlcc/enclave/lib
  tlcc/enclave/mrenclave.go
  tlcc_enclave/.gitignore
  tlcc_enclave/CMakeLists.txt
  tlcc_enclave/Makefile
  tlcc_enclave/README.md
  tlcc_enclave/enclave/CMakeLists.txt
  tlcc_enclave/generate_protos.sh
  utils/fabric-ccenv-sgx/Makefile
Labels: enhancement

#61 Code checks
  Makefile
  build.mk
  ecc/crypto/ecdsa.go
  ecc/crypto/enc_test.go
  ercc/attestation/ias.go
  ercc/attestation/ias_test.go
  ercc/ercc_test.go
  scripts/cpplinter.sh
  scripts/golinter.sh
  tlcc_enclave/generate_protos.sh
Labels: enhancement

#70 fix make docker step
  ecc/Dockerfile
  ecc/Makefile
Labels: bug

#73 Add missing license identifier
  CMakeLists.txt
  Makefile
  build.mk
  cmake/ConfigSGX.cmake
  cmake/Init.cmake
  cmake/NanoPB.cmake
  config.mk
  ecc/Dockerfile
  ecc/Makefile
  ecc/enclave/Makefile
  ecc_enclave/CMakeLists.txt
  ecc_enclave/Makefile
  ecc_enclave/enclave/CMakeLists.txt
  ecc_enclave/generate_mrenclave.sh
  ecc_enclave/sgxcclib/CMakeLists.txt
  ercc/Makefile
  eval/benchmark/executor/executor.go
  eval/benchmark/executor/executor_test.go
  eval/benchmark/executor/worker/worker.go
  eval/benchmark/executor/worker/workerpool.go
  scripts/cpplinter.sh
  tlcc/Makefile
  tlcc_enclave/CMakeLists.txt
  tlcc_enclave/Makefile
  tlcc_enclave/generate_mrenclave.sh
  tlcc_enclave/generate_protos.sh
  utils/fabric-ccenv-sgx/Makefile
Labels: documentation

#57 Support for SGX simulation mode
  README.md
  config.mk
  ercc/Makefile
  ercc/attestation/.gitignore
  ercc/attestation/Makefile
  ercc/attestation/ias.go.template
  ercc/attestation/verifier.go.template
  fabric/0001-sgx-enable-invoked-docker-containers-iff-either-dev-.patch
  fabric/0001-sgx-enable-invoked-docker-containers.patch
  fabric/sgxconfig/demo/start_peer.sh
Labels: enhancement

#75 Fix for PR#73 and minor clean up
  Makefile
  ecc/Makefile
  ecc_enclave/Makefile
  ercc/Makefile
  tlcc_enclave/Makefile
  tlcc_enclave/generate_mrenclave.sh
Labels: bug, enhancement
