Repository hyperledger/fabric-private-chaincode, pull requests merged in 2019-08, with the labels that each got.

#122 Fix concurrency issue in registry
  ecc/enclave/enclave_stub.go
Labels: bug

#127 doc update for plantuml dependencies, addressing issue #126
  README.md
Labels: documentation

#146 Integration test fixes
  fabric/bin/lib/common_utils.sh
  integration/auction_test.sh
  integration/deployment_test.sh
  integration/echo_test.sh
Labels: enhancement
