Repository hyperledger/fabric-private-chaincode, pull requests merged in 2020-06, with the labels that each got.

#353 fpc lifecycle diagram
  docs/design/fabric-v2+/fabric-lifecycle.puml
  docs/design/fabric-v2+/fpc-lifecycle-v2.puml
Labels: documentation

#333 component/registration diagrams
  docs/design/fabric-v2+/fpc-components.puml
  docs/design/fabric-v2+/fpc-registration.puml
Labels: documentation

#376 FPC Management markdown
  docs/design/fabric-v2+/fpc-management.md
Labels: documentation

#375 Updated key distribution diagram
  docs/design/fabric-v2+/fpc-key-dist.puml
Labels: documentation

#377 Update invocation and execution diagrams
  docs/design/fabric-v2+/fpc-cc-execution.puml
  docs/design/fabric-v2+/fpc-cc-invocation.puml
Labels: documentation

#378 Revist FPC validation diagram
  docs/design/fabric-v2+/fpc-validation-msp.puml
  docs/design/fabric-v2+/fpc-validation.puml
Labels: documentation

#379 Update key-mgnt diagram
  docs/design/fabric-v2+/fpc-key-dist.puml
Labels: documentation

#381 Logic fix in ercc-vscc
  fabric/bin/peer.sh
  plugins/ercc-vscc/ercc_validation_logic.go
Labels: bug

#380 Update registration diagram
  docs/design/fabric-v2+/fpc-registration.puml
Labels: documentation

#384 Adding high-level architecture diagrams
  docs/images/FPC arch and lifecycle stages v1.3.pptx
Labels: documentation

#383 Define FPC endorsement policies
  docs/design/fabric-v2+/fpc-management.md
  examples/README.md
  integration/auction_test.sh
  integration/deployment_test.sh
  integration/echo_test.sh
Labels: Test, documentation

#386 UML Diagramm update
  docs/design/fabric-v2+/fpc-cc-invocation.puml
  docs/design/fabric-v2+/fpc-components.puml
  docs/design/fabric-v2+/fpc-registration.puml
  docs/design/fabric-v2+/fpc-validation.puml
Labels: documentation

#389 Update hello world example
  examples/README.md
Labels: documentation

#388 Upgrade Docker-compose network to 2.x and re-enable demo
  Makefile
  demo/Makefile
  demo/README.md
  demo/chaincode/fpc/test.sh
  demo/client/backend/fabric-gateway/auction.json
  demo/client/backend/fabric-gateway/config.json
  demo/client/backend/fabric-gateway/registerUsers.sh
  demo/client/backend/mock/api/serverapi.json
  demo/client/backend/mock/mock_creator.go
  demo/client/frontend/src/components/AuctionDetails.vue
  demo/scenario/Auctioneer1.createAuction.json
  demo/scripts/installCC.sh
  demo/scripts/teardown.sh
  ercc/Makefile
  fabric/bin/peer.sh
  integration/config/configtx.yaml
  plugins/Makefile
  utils/docker-compose/Makefile
  utils/docker-compose/README.md
  utils/docker-compose/network-config/base/base.yaml
  utils/docker-compose/network-config/configtx.yaml
  utils/docker-compose/network-config/core-fpc.yaml
  utils/docker-compose/network-config/core.yaml
  utils/docker-compose/network-config/crypto-config.yaml
  utils/docker-compose/network-config/docker-compose.yml
  utils/docker-compose/network-config/orderer.yaml
  utils/docker-compose/node-sdk/invoke.js
  utils/docker-compose/node-sdk/query.js
  utils/docker-compose/scripts/bootstrap.sh
  utils/docker-compose/scripts/generate.sh
  utils/docker-compose/scripts/lib/common.sh
  utils/docker-compose/scripts/start.sh
  utils/docker/Makefile
  utils/docker/dev/Dockerfile
  utils/docker/peer/Dockerfile
Labels: Demo
