Repository hyperledger/fabric-private-chaincode, pull requests merged in 2020-03, with the labels that each got.

#259 Bump node deps
  demo/client/backend/fabric-gateway/package-lock.json
  demo/client/backend/fabric-gateway/package.json
  demo/client/frontend/package-lock.json
  demo/client/frontend/package.json
  utils/docker-compose/node-sdk/package-lock.json
  utils/docker-compose/node-sdk/package.json
Labels: urgent

#302 Templates for github issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/work-item-template.md
Labels: enhancement

#315 Enable Mock server debug logging
  demo/client/backend/mock/server.go
  ecc/cmd/main.go
Labels: Demo

#318 Docker dev run mounts FPC from local fs
  README.md
  utils/docker/Makefile
Labels: enhancement
